### ISSUE TITLE
npm install failed with peerDependecy error

### ISSUE THREAD

**Issue by jzkunlun** [nsisodiya/flux-inside-web-workers#6]
Is this because react.js is beta version? 

npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-json-viewer@1.0.3 wants react@>= 0.13.3

**Comment by nsisodiya** [comment]
fixed
